DROP TABLE IF EXISTS `DARE_PREPROCES`;

CREATE TABLE DARE_PREPROCES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  STATE INT(11) DEFAULT 0 NOT NULL,
  IP_NAME VARCHAR(255) NOT NULL,
  TS_CREATE DATETIME DEFAULT NULL,
  TS_PROCESSED DATETIME DEFAULT NULL,
  REPOSITORY_ID INT(10) NOT NULL,
  OAI_ID VARCHAR(255) NOT NULL,
  OAI_DATESTAMP VARCHAR(255) NOT NULL,
  LOOKUP VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX `dare_preproces_index` ON DARE_PREPROCES (LOOKUP, OAI_ID, OAI_DATESTAMP, STATE, REPOSITORY_ID);


