CREATE TABLE ERROR_REPORTS (
    DARE_PREPROCES_ID INT(11),
    MESSAGE VARCHAR(1024) DEFAULT NULL,
    URL varchar(1024) DEFAULT NULL,
    STACKTRACE clob,
    STATUS_CODE INT(11) DEFAULT NULL
);

CREATE INDEX ERROR_REPORTS_index ON ERROR_REPORTS (STATUS_CODE);
