DROP TABLE IF EXISTS `record_status`;

CREATE TABLE record_status (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  STATE INT(11) DEFAULT 0 NOT NULL,
  IP_NAME VARCHAR(255) NOT NULL,
  TS_CREATE DATETIME DEFAULT NULL,
  TS_PROCESSED DATETIME DEFAULT NULL,
  REPOSITORY_ID INT(10) NOT NULL,
  OAI_ID VARCHAR(255) NOT NULL,
  OAI_DATESTAMP VARCHAR(255) NOT NULL,
  LOOKUP VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX `record_status_index` ON record_status (LOOKUP, OAI_ID, OAI_DATESTAMP, STATE, REPOSITORY_ID);